name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: '>=2.15.0 <7.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  flutter_webrtc: 0.9.22
  shared_preferences: any
  http: any
  path_provider: any
  audio_session: ^0.1.23

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
